name: flutter_show
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/flutter.png
    - assets/images/github.png
    - assets/images/userImage.png
    - assets/images/themespace.png

    - assets/images/assets/icon.png
    - assets/images/assets/image.png

    - assets/images/basics/column.png
    - assets/images/basics/container.png
    - assets/images/basics/layout-structure-regions-mobile.png
    - assets/images/basics/material-app-bar.png
    - assets/images/basics/material-raised-button.png
    - assets/images/basics/row.png
    - assets/images/basics/text.png
    - assets/images/basics/app_bar.png

    - assets/images/cupertino/cupertino-action-sheet.png
    - assets/images/cupertino/cupertino-activity-indicator.png
    - assets/images/cupertino/cupertino-alert-dialog.png
    - assets/images/cupertino/cupertino-button.png
    - assets/images/cupertino/cupertino-date-picker.png
    - assets/images/cupertino/cupertino-dialog-action.png
    - assets/images/cupertino/cupertino-dialog.png
    - assets/images/cupertino/cupertino-fullscreen-dialog-transition.png
    - assets/images/cupertino/cupertino-nav-bar.png
    - assets/images/cupertino/cupertino-page-scaffold.png
    - assets/images/cupertino/cupertino-page-transition.png
    - assets/images/cupertino/cupertino-picker.png
    - assets/images/cupertino/cupertino-scrollbar.png
    - assets/images/cupertino/cupertino-segmented-control.png
    - assets/images/cupertino/cupertino-slider.png
    - assets/images/cupertino/cupertino-switch.png
    - assets/images/cupertino/cupertino-tab-bar.png
    - assets/images/cupertino/cupertino-tab-scaffold.png
    - assets/images/cupertino/cupertino-tab-view.png
    - assets/images/cupertino/cupertino-textfield.png
    - assets/images/cupertino/cupertino-timer-picker.png

    - assets/images/interaction/heroes.png

    - assets/images/layout/align.png
    - assets/images/layout/aspect-ratio.png
    - assets/images/layout/baseline.png
    - assets/images/layout/center.png
    - assets/images/layout/components-grid-lists.png
    - assets/images/layout/constrained-box.png
    - assets/images/layout/material-list-tile.png
    - assets/images/layout/padding.png
    - assets/images/layout/sized-box.png
    - assets/images/layout/stack.png
    - assets/images/layout/transform.png

    - assets/images/material/components-buttons-other.png
    - assets/images/material/components-buttons-usage.png
    - assets/images/material/components-dialogs.png
    - assets/images/material/components-expansion-panels.png
    - assets/images/material/components-grid-lists.png
    - assets/images/material/components-menus.png
    - assets/images/material/components-pickers.png
    - assets/images/material/components-steppers.png
    - assets/images/material/material-alert-dialog.png
    - assets/images/material/material-app-bar.png
    - assets/images/material/material-bottom-navigation-bar.png
    - assets/images/material/material-bottom-sheets.png
    - assets/images/material/material-button-bar.png
    - assets/images/material/material-card.png
    - assets/images/material/material-checkbox.png
    - assets/images/material/material-chip.png
    - assets/images/material/material-circular-progress-indicator.png
    - assets/images/material/material-data-table.png
    - assets/images/material/material-divider.png
    - assets/images/material/material-drawer.png
    - assets/images/material/material-floating-action-button.png
    - assets/images/material/material-linear-progress-indicator.png
    - assets/images/material/material-list-tile.png
    - assets/images/material/material-popup-menu-button.png
    - assets/images/material/material-radio.png
    - assets/images/material/material-raised-button.png
    - assets/images/material/material-slider.png
    - assets/images/material/material-snack-bar.png
    - assets/images/material/material-switch.png
    - assets/images/material/material-tab-bar.png
    - assets/images/material/material-text-field.png
    - assets/images/material/material-tooltip.png
    - assets/images/material/material-widgets-app.png
    - assets/images/material/materialdesign-introduction.png

    - assets/images/painting/clip-oval.png
    - assets/images/painting/clip-rect.png
    - assets/images/painting/custom-paint.png
    - assets/images/painting/decorated-box.png
    - assets/images/painting/opacity.png
    - assets/images/painting/transform.png

    - assets/images/scrolling/patterns-swipe-to-refresh.png

    - assets/data/widget/widget_list.json
    - assets/data/widget/accessibility.json
    - assets/data/widget/animation.json
    - assets/data/widget/assets.json
    - assets/data/widget/async.json
    - assets/data/widget/basics.json
    - assets/data/widget/cupertino.json
    - assets/data/widget/input.json
    - assets/data/widget/interaction.json
    - assets/data/widget/layout.json
    - assets/data/widget/material.json
    - assets/data/widget/painting.json
    - assets/data/widget/scrolling.json
    - assets/data/widget/styling.json
    - assets/data/widget/text.json
